name: yt
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4  #
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  shared_preferences_android: ^2.4.7
  google_maps_flutter: ^2.5.0 # Use the latest compatible version
  google_maps_webservice: ^0.0.7 # Correct version for Places API usage
  geolocator: ^12.0.0
  geolocator_android: ^4.3.1
  http: ^0.13.6
  carousel_slider: ^5.0.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.17.5
  firebase_messaging: ^14.9.4
  webviewx: ^0.2.2
  # path: ^1.8.0

dev_dependencies:
  #  lints: ^5.1.1
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/